name: zi2zi-env
channels:
  - pytorch
  - defaults
dependencies:
  - numpy=1.18.1
  - scipy=1.4.1
  - imageio=2.8.0
  - matplotlib
  - pip:
    - torch==1.8.0
    - torchvision==0.9.0
    - pillow==7.1.2
    - opencv-python
    - fontTools
    - tdqm
